import type { ParamMeta } from "./analyticsParamMeta";

export const PARAM_META_WHEN: Record<string, ParamMeta> = {
  session_label: {
    label: "Session",
    category: "when",
    description: "Which FX session the signal fired in",
    unit: null,
    bucketMap: {
      ASIAN: "Asian",
      LONDON: "London",
      NY_OVERLAP: "NY Overlap",
      NY_LATE: "NY Late",
      CLOSE: "Close",
    },
  },
  day_of_week: {
    label: "Weekday",
    category: "when",
    description: "Weekday the signal fired",
    unit: null,
    bucketMap: {
      "0": "Monday",
      "1": "Tuesday",
      "2": "Wednesday",
      "3": "Thursday",
      "4": "Friday",
    },
  },
  minutes_into_session: {
    label: "Minutes Into Session",
    category: "when",
    description: "Minutes elapsed since the current session started",
    unit: null,
  },
  hour_bucket: {
    label: "Hour Bucket",
    category: "when",
    description: "Finer-grained session split isolating London open",
    unit: null,
    bucketMap: {
      ASIAN_QUIET: "Asian Quiet",
      LONDON_OPEN: "London Open",
      LONDON_NY: "London/NY",
      NY_LATE_CLOSE: "NY Late/Close",
    },
  },
  kill_zone: {
    label: "Kill Zone",
    category: "when",
    description: "ICT kill zone at signal time (NY timezone)",
    unit: null,
    bucketMap: {
      asian_kz: "Asian KZ",
      london_kz: "London KZ",
      ny_am_kz: "NY AM KZ",
      ny_lunch: "NY Lunch",
      ny_pm_kz: "NY PM KZ",
      dead_zone: "Dead Zone",
    },
  },
  resolution_candles_param: {
    label: "Bars to Resolution",
    category: "when",
    description: "How many bars from signal to TP/SL hit — fast resolutions indicate cleaner setups",
    unit: "candles",
  },
};

export const PARAM_META_SETUP: Record<string, ParamMeta> = {
  fvg_age: {
    label: "FVG Age",
    category: "setup",
    description: "How many M15 candles old the gap is when the signal fires",
    unit: "candles",
  },
  fvg_width_pips: {
    label: "FVG Width",
    category: "setup",
    description: "Gap size in pips",
    unit: "pips",
  },
  fvg_width_atr_ratio: {
    label: "FVG Width ÷ ATR",
    category: "setup",
    description: "Gap size as a multiple of recent volatility",
    unit: "x",
  },
  wick_penetration_ratio: {
    label: "Wick Penetration",
    category: "setup",
    description: "How deep the signal wick reached into the gap",
    unit: "%",
    isRatio01: true,
  },
  rejection_body_ratio: {
    label: "Rejection Body",
    category: "setup",
    description: "Close position inside the signal candle's range",
    unit: "%",
    isRatio01: true,
  },
  bos_used: {
    label: "BOS Used",
    category: "setup",
    description: "Whether a break-of-structure confirmation was used",
    unit: null,
    bucketMap: {
      True: "Yes",
      False: "No",
    },
  },
  body_pips: {
    label: "Candle Body",
    category: "setup",
    description: "Signal candle body size in pips — display-only, not cross-pair comparable (use Body ÷ ATR for analytics)",
    unit: "pips",
  },
  candle_efficiency: {
    label: "Candle Efficiency",
    category: "setup",
    description: "Body as a share of the candle's full range",
    unit: "%",
    isRatio01: true,
  },
  close_wick_ratio: {
    label: "Rejection Wick",
    category: "setup",
    description: "Rejection wick as a share of the candle's range",
    unit: "%",
    isRatio01: true,
  },
  body_atr_ratio: {
    label: "Body ÷ ATR",
    category: "setup",
    description: "Candle body as a multiple of recent volatility",
    unit: "x",
  },
  dist_to_round_atr: {
    label: "Distance to Round ÷ ATR",
    category: "setup",
    description: "Distance from entry to nearest 50-pip round level, in ATR units",
    unit: "x",
  },
  fvg_breathing_room_pips: {
    label: "Breathing Room",
    category: "setup",
    description: "Pips between the signal close and the FVG near edge",
    unit: "pips",
  },
  rejection_wick_atr: {
    label: "Rejection Wick ÷ ATR",
    category: "setup",
    description: "Rejection wick length as a multiple of recent volatility",
    unit: "x",
  },
  opposing_wick_ratio: {
    label: "Opposing Wick",
    category: "setup",
    description: "Wick on the wrong side of the trade as a share of range",
    unit: "%",
    isRatio01: true,
  },
  fvg_width_spread_mult: {
    label: "FVG Width ÷ Spread",
    category: "setup",
    description: "How many spread-widths the FVG spans",
    unit: "x",
  },
  h1_fvg_contains_entry: {
    label: "H1 FVG Confluence",
    category: "setup",
    description: "Entry sits inside an active H1 FVG",
    unit: null,
    bucketMap: { True: "Yes", False: "No" },
  },
  signal_wick_pips: {
    label: "Rejection Wick (pips)",
    category: "setup",
    description: "Absolute length of the rejection wick at the signal bar",
    unit: "pips",
  },
  sl_swing_distance_bars: {
    label: "BOS Swing Distance",
    category: "setup",
    description: "M15 bars between the signal and the BOS swing it stops behind",
    unit: "candles",
  },
  bos_swing_leg_atr: {
    label: "BOS Leg ÷ ATR",
    category: "setup",
    description: "Size of protected swing leg as an ATR multiple",
    unit: "x",
  },
  open_wick_pips: {
    label: "Open-Side Wick",
    category: "setup",
    description: "Raw open-side wick in pips (tolerance dilution check)",
    unit: "pips",
  },
  open_wick_zero: {
    label: "Strict Wickless",
    category: "setup",
    description: "True only when open-side wick is exactly zero",
    unit: null,
    bucketMap: { True: "Strict", False: "Near" },
  },
  range_atr_ratio: {
    label: "Range ÷ ATR",
    category: "setup",
    description: "Full signal candle range as an ATR multiple",
    unit: "x",
  },
  gap_pips: {
    label: "Open Gap",
    category: "setup",
    description: "Gap from prior close to signal open, in pips",
    unit: "pips",
  },
};
